---
- name: Configure webserver with nginx
  hosts: webservers
  sudo: True
  tasks:
    - name: create user
      user: name=deploy uid=1000 groups=www-data home=/deploy/ shell=/bin/bash
    - name: create projects dir
      file: path=/deploy/projects state=directory
    - name: install packages
      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
      with_items:
        - php5
        - php5-fpm
        - nginx
        - vim
        - nfs-common
    - name: mount project
      mount:
        name: /deploy/projects/
        src: 192.168.56.1:/srv/nfs/personal_projects/
        fstype: nfs
        opts: user,rw,proto=tcp,hard,intr,rsize=8192,wsize=8192,noatime
        fstab: /etc/fstab
        state: mounted
    - name: copy nginx config file
      copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default
    - name: enable configuration
      file: >
        dest=/etc/nginx/sites-enabled/default
        src=/etc/nginx/sites-available/default
        state=link
    - name: restart services
      service: name={{ item }} state=restarted
      with_items:
        - nginx
        - php5-fpm
